from .OLO_ResolutionPreset import NODE_CLASS_MAPPINGS as RESOLUTION_PRESET_MAPPINGS
from .OLO_ResolutionPreset import NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_PRESET_DISPLAY_MAPPINGS

from .OLO_WanFrame import NODE_CLASS_MAPPINGS as WAN_FRAME_MAPPINGS
from .OLO_WanFrame import NODE_DISPLAY_NAME_MAPPINGS as WAN_FRAME_DISPLAY_MAPPINGS
from .OLO_FrameHold import NODE_CLASS_MAPPINGS as FRAME_HOLD_MAPPINGS
from .OLO_FrameHold import NODE_DISPLAY_NAME_MAPPINGS as FRAME_HOLD_DISPLAY_MAPPINGS
from .OLO_LastFrame import NODE_CLASS_MAPPINGS as LAST_FRAME_MAPPINGS
from .OLO_LastFrame import NODE_DISPLAY_NAME_MAPPINGS as LAST_FRAME_DISPLAY_MAPPINGS
from .OLO_FirstLastFrame import NODE_CLASS_MAPPINGS as FIRST_LAST_FRAME_MAPPINGS
from .OLO_FirstLastFrame import NODE_DISPLAY_NAME_MAPPINGS as FIRST_LAST_FRAME_DISPLAY_NAME_MAPPINGS
from .OLO_ModelShare import NODE_CLASS_MAPPINGS as MODEL_SHARE_MAPPINGS
from .OLO_ModelShare import NODE_DISPLAY_NAME_MAPPINGS as MODEL_SHARE_DISPLAY_MAPPINGS
from .OLO_AudioConcat import NODE_CLASS_MAPPINGS as AUDIO_CONCAT_MAPPINGS
from .OLO_AudioConcat import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_CONCAT_DISPLAY_MAPPINGS
from .OLO_AudioInfo import NODE_CLASS_MAPPINGS as AUDIO_INFO_MAPPINGS
from .OLO_AudioInfo import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_INFO_DISPLAY_MAPPINGS
from .OLO_TestTextOutput import NODE_CLASS_MAPPINGS as TEST_TEXT_OUTPUT_MAPPINGS
from .OLO_TestTextOutput import NODE_DISPLAY_NAME_MAPPINGS as TEST_TEXT_OUTPUT_DISPLAY_MAPPINGS
from .OLO_DrawPoseKeypoint import NODE_CLASS_MAPPINGS as DRAW_POSE_KEYPOINT_MAPPINGS
from .OLO_DrawPoseKeypoint import NODE_DISPLAY_NAME_MAPPINGS as DRAW_POSE_KEYPOINT_DISPLAY_MAPPINGS
from .OLO_KeypointSelector import NODE_CLASS_MAPPINGS as KEYPOINT_SELECTOR_MAPPINGS
from .OLO_KeypointSelector import NODE_DISPLAY_NAME_MAPPINGS as KEYPOINT_SELECTOR_DISPLAY_MAPPINGS
from .OLO_Code import NODE_CLASS_MAPPINGS as CODE_MAPPINGS
from .OLO_Code import NODE_DISPLAY_NAME_MAPPINGS as CODE_DISPLAY_MAPPINGS


NODE_CLASS_MAPPINGS = {
    **RESOLUTION_PRESET_MAPPINGS,
    ** WAN_FRAME_MAPPINGS,
    **FRAME_HOLD_MAPPINGS,
    **LAST_FRAME_MAPPINGS,
    **FIRST_LAST_FRAME_MAPPINGS,
    **MODEL_SHARE_MAPPINGS,
    **AUDIO_CONCAT_MAPPINGS,
    **AUDIO_INFO_MAPPINGS,
    **TEST_TEXT_OUTPUT_MAPPINGS,
    **DRAW_POSE_KEYPOINT_MAPPINGS,
    **KEYPOINT_SELECTOR_MAPPINGS,
    **CODE_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    ** RESOLUTION_PRESET_DISPLAY_MAPPINGS,
    **WAN_FRAME_DISPLAY_MAPPINGS,
    ** FRAME_HOLD_DISPLAY_MAPPINGS,
    **LAST_FRAME_DISPLAY_MAPPINGS,
    **FIRST_LAST_FRAME_DISPLAY_NAME_MAPPINGS,
    **MODEL_SHARE_DISPLAY_MAPPINGS,
    **AUDIO_CONCAT_DISPLAY_MAPPINGS,
    **AUDIO_INFO_DISPLAY_MAPPINGS,
    **TEST_TEXT_OUTPUT_DISPLAY_MAPPINGS,
    **DRAW_POSE_KEYPOINT_DISPLAY_MAPPINGS,
    **KEYPOINT_SELECTOR_DISPLAY_MAPPINGS,
    **CODE_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

WEB_DIRECTORY = "web"
